# Use root/example as user/password credentials
version: '3.1'

services:
  keycloak:
    image:  jboss/keycloak
    ports:
      - "9402:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      # DB_VENDOR: POSTGRES
      # DB_ADDR: postgres1
      # DB_DATABASE: postgres
      # DB_USER: postgres
      # DB_SCHEMA: public
      # DB_PASSWORD: test123ewqasd
      KEYCLOAK_LOGLEVEL: "DEBUG"
      WILDFLY_LOGLEVEL: "DEBUG"
    # depends_on:
    #   - postgres
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  # postgres:
  #   image: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=test123ewqasd
  #   volumes:
  #     - posgresqlData1:/var/lib/postgresql
  #   ports:
  #     - "9404:5432"
  
  # mongo:
  #   image: mongo:3.6
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example

# volumes:
#   posgresqlData1: