version: "3"

services:
  keycloak:
    image:  jboss/keycloak
    ports:
      - "9402:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres1
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: test123ewqasd
      KEYCLOAK_LOGLEVEL: "DEBUG"
      WILDFLY_LOGLEVEL: "DEBUG"
