version: "3"

services:
  postgres:
    image: docker.io/bitnami/postgresql:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "9404:5432"

